/* global module */
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    fontFamily: {
      sans: ["var(--font-outfit)", "sans-serif"],
    },
    extend: {
      fontSize: {
        mini: "12px",
        small: "13px",
        textSm: "14px",
        regular: "15px",
        textBase: "16px",
        textBasePlus: "17px",
        textMd: "18px",
        textMdPlus: "19px",
        textLg: "20px",
        textLgPlus: "21px",
        titleSm: "22px",
        titleBase: "23px",
        titleMid: "24px",
        titleMidPlus: "25px",
        titleSemiMd: "26px",
        titleSemiMdPlus: "27px",
        titleMd: "28px",
        titleMdPlus: "29px",
        titleXl: "30px",
        titleXlPlus: "31px",
        titleLg: "32px",
        titleLgPlus: "33px",
        titleXxl: "34px",
        titleXxlPlus: "35px",
        titleXxlPlusPlus: "36px",
        titleXxxl: "42px",
        titleXxxlPlus: "48px",
        titleHuge: "62px",
      },
      fontWeight: {
        extraLight: "300",
        light: "400",
        medium: "500",
        bold: "600",
        extraBold: "700",
      },
      colors: {
        primary: "#5015FF",
        light: "#F4F3EC",
        lightGray: "#F9FAFB",
        coolGray: "#ACB5BB",
        deepGray: "#8C8E8F",
        lightGrayBeta: "#F1F1F1",
        darkGray: "#1A1C1E",
        softGray: "#E3E7EA",
        beige: "#F4F3ED",
        paleGray: "#DFDFE0",
        ultraLightGray: "#F8F8F8",
        mediumLightGray: "#E5E5E5",
        greenDark: "#007832",
        greenBright: "#2FEB7D",
        yellowDark: "#854D0E",
        yellowBright: "#FEF9C3",
        yellowPastel: "#FFF493",
        blackTransparent: "#00000033",
        softGreen: "#A3B8A2",
        lavenderLight: "#F6F3FF",
        mintGreen: "#B6E2C1",
        lightAshGray: "#EDF1F3",
        periwinkleLight: "#EFF0F6",
        mediumGray: "#757575",
        neutralGray: "#D9D9D9",
        richBlack: "#1E1E1E",
        mintLight: "#EBFDF2",
        greenPrimary: "#0AAC53",
        silverGray: "#CDCDCD",
        lavenderUltraLight: "#F7F4FF",
        darkPurple: "#9215FF",
        orangePrimary: "#EB672F",
        salmon: "#F9645F",
        obsidianBlack: "#181818",
        deepTeal: "#0B7C68",
        tealGreen: "#0AAC53",
        tealGreenLight: "#B6E2C1",
        tealGreenPale: "#EBFDF2",
        charcoalPale: "#1818181A",
        lemonTint: "#EDFACC",
        mintPastel: "#D4FCD9",
        aquaMist: "#E9F5F3",
        offWhite: "#F9F9F9",
        whitePrimary : "#FFFFFF",
        stoneGray: "#999999",
        mintUltraLight: "#F4FAF9",
        graySoft: "#E0E0E0",
        redPrimary: "#F14336",
        lightGrayAlpha: "#F5F5F5",
        charcoalGrey: "#202224",
        emrladGreen: "#28B446",
        vividBlue: "#518EF8",
        bluePrimary: "#518EF8",
        orangeAccent: "#FF541B",
        yellowPrimary: "#FDC700",
        lightGrayGamma: "#EAEAEA",
        grayDelta: "#DDDDDD",
        charcoalBlack : "#1C1C1C",
        goldenYellow : "#FFC720",
        saffronYellow : "#E2A900"
      },
      backgroundImage: {
        cyanGradient:
          "linear-gradient(92.64deg, rgba(47, 157, 138, 0.05) 0%, rgba(11, 124, 104, 0.05) 100%)",
      },
      borderRadius: {
        custom: "10px",
        rounder: "5px",
      },
      maxWidth: {
        container: "1600px",
        content: "1352px",
      },
    },
    screens: {
      xxs: "380px",
      xs: "480px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      desktop: "1440px",
      figmascreen: "1600px",
      widescreen: "1778px",
      fullhd: "1920px",
      ultrawide: "2560px",
      megawide: "3440px",
    },
  },
  plugins: [],
  corePlugins: {
    preflight: false,
  },
};
