export const routePath = {
  home: "/home",
  logIn: "/login",
  dashboard: "/dashboard",
  profile: "/my-profile",
  settings: "settings",
  messages: "/messages",
  offers: "/offers",
  projects: "/projects",
  myProjects: "/my-projects",
  myOffers: "/my-offers",
  register: "/register",
  createPassword: "/create-password",
  verify: "/verify",
  resetPassword: "/reset-password",
  resetPasswordSuccess: "/password-reset-success",
  forgotPassword: "/forgot-password",
  businessProfile: (id: string) => `/business-profile/${id}`,
  businessProfileBase: "/business-profile",
  projectBase: "/project",
  project: (id: string) => `/project/${id}`,
  createProjectSelectService: "/create-project/select-service",
  createProjectProjectDescription : "/create-project/project-description",
  createProjectProjectLocation : "/create-project/project-location",
  createProjectContactInformation : "/create-project/contact-details",
  accessDenied: "/access-denied",
  subscription: "/subscriptions",
  userProfileBase: (id: string) => `/user-profile/${id}`,
  userProfile: "/user-profile",
};
